---
title: "OrganicChemistryUnknown_progress_report"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

The purpose of the project is to generate a search engine that will assist in narrowing the list of OBU organic unknowns based off of the following criteria:melting point, boiling point, whether the compound is a solid or liqid at room temperature, and high priority functional groups. The project will contain 3 main phases that are listed as followed.

Phase 1: compilation of data to satisfy the criteria needed to generate an output.

Phase 2: organization of the compiled data via tidy data standards, in order to finalize the database.

Phase 3: joining the data in an SQL process.

Phase 4: creation of the of the webpage and generating the interface.

The group is currently in phase 1 and the work shall be divided by inividually compiling the data by functional group. Listed below is the division of functional groups by group member:

Rachel: acetals, acid anyhydrides, acid halides, alcohols, aldehydes, alkanes, alkenes, amines, arylalkanes, and AzoCompounds

Jake: Amides; HeterocyclicCompounds; Hydrazines,Hydrazides; Imides; Ketones; Nitrates,Nitrites; Nitriles; Nitro-containingCompounds; Oximes; Phenols; PhosphorousCompounds


Devin: Quinones; Sulfates; Sulfides; Sulfocompounds; Thiols; Ureas; Monomers for polymers; Misc. compounds



Reid: carbamates; carbanilides; carbohydrates; carboxylicacids; cyanates; isoesters; thioesters; ethers; guanidines

Resources:
https://pubchem.ncbi.nlm.nih.gov/
https://www.chemicalbook.com/.
https://www.sigmaaldrich.com/US.
https://www.fishersci.com/ 
https://stackoverflow.com/
https://en.wikipedia.org/
all information is currently being entered into an excel spreadsheet; all questions are being presented to Dr. Malmberg along with the course guidline materials.

Responsibilites for each phase to follow will be assigned after meeting with Dr. Malmberg.



Summary of project:
  We took the compounds from the list of possible Organic Chemistry Lab Unknowns, and compiled them in an Excel spreadsheet, including for each compound
  the melting point, boiling point, physical state at room temperature, and any notable functional groups that were included in each compound.
  This spreadsheet was then saved as a .csv file so the values could be queried from the spreadsheet in an SQL database.
  Finally, a Python code was written to create a search engine that would query chemical compounds that could be selected based on specified physical 
  state, melting point, boiling point, and functional groups.
  

Contributions by each member:

Devin:

Jake: creating the group GitHub repository, entering the information for my part of the compounds in the Excel spreadsheet, 
writing about 40% of the python code (with assistance from Dr. Malmberg), writing some of the descriptions of our project in the RMarkdown document.

Rachel: Entering approximately 350-400 compounds into the database, compiling the SQL database (with assistance from Dr.Malmberg),
writing the first block of code for the interfacting questions (with assistance from Dr.Malmberg), starting and writing 60% of the progress report 
RMarkdown file. 

Reid:Entering compounds into the database, editing some of the code for working purposes, writing explinations of what the lines of code do so that someone can recreate the code if need be.

Acknowledgement: We would like to thank Dr. Malmberg for his patience with us during this project, we were in need of much assistance and were blessed
with the opportunity to lean much about programming from him.
